import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import ClientProviders from "../components/ClientProviders";
import AuthButton from '../components/AuthButton';
import Link from 'next/link';

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable} antialiased bg-gray-50`}>
        <ClientProviders>
          <div className="min-h-screen flex">
            {/* Sidebar */}
            <aside className="hidden md:flex flex-col w-64 bg-white shadow-lg p-6 gap-8 fixed inset-y-0 left-0 z-20">
              <Link href="/" className="text-3xl font-extrabold tracking-tight text-blue-700 mb-8">TrendWise</Link>
              <div className="flex flex-col gap-4">
                <AuthButton />
                <Link href="/article/create" className="mt-4 px-4 py-2 bg-blue-600 text-white rounded font-semibold text-center hover:bg-blue-700 transition">Create Article</Link>
              </div>
            </aside>
            {/* Mobile sidebar toggle (optional) */}
            {/* Main content */}
            <main className="flex-1 md:ml-64 w-full">
              {children}
            </main>
          </div>
        </ClientProviders>
      </body>
    </html>
  );
}
